version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - restaurant-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - restaurant-network

  frontend:
    build: ./services/frontend
    ports:
      - "5173:5173"
    depends_on:
      - restaurant-manager
    networks:
      - restaurant-network
    volumes:
      - ./services/frontend:/app
      - /app/node_modules

  restaurant-manager:
    build: ./services/restaurant-manager
    ports:
      - "3004:3004"
      - "8082:8082"  # WebSocket
      - "8083:8083"
    depends_on:
      - kafka
    networks:
      - restaurant-network
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./shared:/app/shared

  kitchen-service:
    build: ./services/kitchen-service
    ports:
      - "3002:3002"
    depends_on:
      - kafka
    networks:
      - restaurant-network
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./shared:/app/shared

  warehouse-service:
    build: ./services/warehouse-service
    ports:
      - "3003:3003"
    depends_on:
      - kafka
    networks:
      - restaurant-network
    environment:
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./shared:/app/shared

networks:
  restaurant-network:
    driver: bridge
